### ISSUE TITLE
Other programs exist 

### ISSUE THREAD

**Issue by ghost** [smangul1/command-line-teaching#1]
(Watson-Haigh et al. 2013; Via et al. 2011)

**Comment by smangul1** [comment]
Can you please provide the full citation for Via et al. 2011

**Comment by ghost** [comment]
http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1002245

Via, A., De Las Rivas, J., Attwood, T.K., Landsman, D., Brazas, M.D.,
Leunissen, J.A., Tramontano, A. and Schneider, M.V., 2011. Ten simple rules
for developing a short bioinformatics training course. *PLoS Comput Biol*,
*7*(10), p.e1002245.



Lana S. Martin, MA, PhD

Staff Research Associate
ZarLab Computational Genetics at UCLA
zarlab.cs.ucla.edu

**Comment by smangul1** [comment]
done!
